### ISSUE TITLE
📒Add ability to load from file

### ISSUE THREAD

**Issue by newtoallofthis123** [newtoallofthis123/envn#1]
This one is a big one.

So you basically either add a load file option or ask for it and then loop through the entries

I guess the parsing can be done through some regex

The entries should not only be added to the memory, but also the global encrypted database

**Comment by nisargparikh69** [comment]
what should be format of text inside loadfile to read/parse ? Should  secret name, key and value should separated by some character or some other format!?

**Comment by newtoallofthis123** [comment]
It should follow standard `.env` rules:

```bash
KEY=VALUE
```

alternatively, let's also support

```bash
export KEY=VALUE
```

**Comment by nisargparikh69** [comment]
there is name identifier as well right? its not just key and value ! thats why i asked as there are 3 things to store in DB

**Comment by newtoallofthis123** [comment]
True...how about a simple parser that converts the capital KEY to a smaller `key`Maybe we can also give the user an option to edit them as it is loaded

**Comment by nisargparikh69** [comment]
Sorry but I think, I am getting confused on goal of project itself. It I would be great if you could just mention bullet points of goal in README.md itself.
If goal is to store key / values of env file as per name , by name i mean you are referring to different section / profile like each project has diff profile for its own env., Why current project structure is having only 1 key / value per name !? any code directory would have multiple key value in single .env file if I am not wrong!

If requirement is clear, I can come up with solution to load config enhancement clearly

**Comment by newtoallofthis123** [comment]
I'm sorry if I explained poorly

What I meant was
Let's say that this is our .env file that we want to take all the key and values from;

```bash
HELLO=HI
SECRET=TOP
COOL=GUY
```

Okay...so our goal is to store all of this into the db like this:

key=HELLO
value=HI
name=tolower(HELLO)/ask the user
